// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StatusCode.proto

package com.loncent.protocol.stauscode;

public final class StatusCode {
  private StatusCode() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface StatusCodeResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int32 popstr = 1;
    boolean hasPopstr();
    int getPopstr();
    
    // optional int32 type = 2;
    boolean hasType();
    int getType();
  }
  public static final class StatusCodeResponse extends
      com.google.protobuf.GeneratedMessage
      implements StatusCodeResponseOrBuilder {
    // Use StatusCodeResponse.newBuilder() to construct.
    private StatusCodeResponse(Builder builder) {
      super(builder);
    }
    private StatusCodeResponse(boolean noInit) {}
    
    private static final StatusCodeResponse defaultInstance;
    public static StatusCodeResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public StatusCodeResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.loncent.protocol.stauscode.StatusCode.internal_static_com_loncent_protocol_StatusCodeResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.loncent.protocol.stauscode.StatusCode.internal_static_com_loncent_protocol_StatusCodeResponse_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int32 popstr = 1;
    public static final int POPSTR_FIELD_NUMBER = 1;
    private int popstr_;
    public boolean hasPopstr() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getPopstr() {
      return popstr_;
    }
    
    // optional int32 type = 2;
    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getType() {
      return type_;
    }
    
    private void initFields() {
      popstr_ = 0;
      type_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, popstr_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, type_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, popstr_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, type_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.loncent.protocol.stauscode.StatusCode.StatusCodeResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.loncent.protocol.stauscode.StatusCode.StatusCodeResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.loncent.protocol.stauscode.StatusCode.StatusCodeResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.loncent.protocol.stauscode.StatusCode.StatusCodeResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.loncent.protocol.stauscode.StatusCode.StatusCodeResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.loncent.protocol.stauscode.StatusCode.StatusCodeResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.loncent.protocol.stauscode.StatusCode.StatusCodeResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.loncent.protocol.stauscode.StatusCode.StatusCodeResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.loncent.protocol.stauscode.StatusCode.StatusCodeResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.loncent.protocol.stauscode.StatusCode.StatusCodeResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.loncent.protocol.stauscode.StatusCode.StatusCodeResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.loncent.protocol.stauscode.StatusCode.StatusCodeResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.loncent.protocol.stauscode.StatusCode.internal_static_com_loncent_protocol_StatusCodeResponse_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.loncent.protocol.stauscode.StatusCode.internal_static_com_loncent_protocol_StatusCodeResponse_fieldAccessorTable;
      }
      
      // Construct using com.loncent.protocol.stauscode.StatusCode.StatusCodeResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        popstr_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.loncent.protocol.stauscode.StatusCode.StatusCodeResponse.getDescriptor();
      }
      
      public com.loncent.protocol.stauscode.StatusCode.StatusCodeResponse getDefaultInstanceForType() {
        return com.loncent.protocol.stauscode.StatusCode.StatusCodeResponse.getDefaultInstance();
      }
      
      public com.loncent.protocol.stauscode.StatusCode.StatusCodeResponse build() {
        com.loncent.protocol.stauscode.StatusCode.StatusCodeResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.loncent.protocol.stauscode.StatusCode.StatusCodeResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.loncent.protocol.stauscode.StatusCode.StatusCodeResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.loncent.protocol.stauscode.StatusCode.StatusCodeResponse buildPartial() {
        com.loncent.protocol.stauscode.StatusCode.StatusCodeResponse result = new com.loncent.protocol.stauscode.StatusCode.StatusCodeResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.popstr_ = popstr_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.loncent.protocol.stauscode.StatusCode.StatusCodeResponse) {
          return mergeFrom((com.loncent.protocol.stauscode.StatusCode.StatusCodeResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.loncent.protocol.stauscode.StatusCode.StatusCodeResponse other) {
        if (other == com.loncent.protocol.stauscode.StatusCode.StatusCodeResponse.getDefaultInstance()) return this;
        if (other.hasPopstr()) {
          setPopstr(other.getPopstr());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              popstr_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              type_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 popstr = 1;
      private int popstr_ ;
      public boolean hasPopstr() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getPopstr() {
        return popstr_;
      }
      public Builder setPopstr(int value) {
        bitField0_ |= 0x00000001;
        popstr_ = value;
        onChanged();
        return this;
      }
      public Builder clearPopstr() {
        bitField0_ = (bitField0_ & ~0x00000001);
        popstr_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 type = 2;
      private int type_ ;
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getType() {
        return type_;
      }
      public Builder setType(int value) {
        bitField0_ |= 0x00000002;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.loncent.protocol.StatusCodeResponse)
    }
    
    static {
      defaultInstance = new StatusCodeResponse(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.loncent.protocol.StatusCodeResponse)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_loncent_protocol_StatusCodeResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_loncent_protocol_StatusCodeResponse_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020StatusCode.proto\022\024com.loncent.protocol" +
      "\"2\n\022StatusCodeResponse\022\016\n\006popstr\030\001 \001(\005\022\014" +
      "\n\004type\030\002 \001(\005B \n\036com.loncent.protocol.sta" +
      "uscode"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_loncent_protocol_StatusCodeResponse_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_loncent_protocol_StatusCodeResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_loncent_protocol_StatusCodeResponse_descriptor,
              new java.lang.String[] { "Popstr", "Type", },
              com.loncent.protocol.stauscode.StatusCode.StatusCodeResponse.class,
              com.loncent.protocol.stauscode.StatusCode.StatusCodeResponse.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
