// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CheckToken.proto

package com.loncent.protocol.inner;

public final class CheckToken {
  private CheckToken() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CheckTokenRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string accountName = 1;
    boolean hasAccountName();
    String getAccountName();
    
    // optional int64 token = 2;
    boolean hasToken();
    long getToken();
  }
  public static final class CheckTokenRequest extends
      com.google.protobuf.GeneratedMessage
      implements CheckTokenRequestOrBuilder {
    // Use CheckTokenRequest.newBuilder() to construct.
    private CheckTokenRequest(Builder builder) {
      super(builder);
    }
    private CheckTokenRequest(boolean noInit) {}
    
    private static final CheckTokenRequest defaultInstance;
    public static CheckTokenRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public CheckTokenRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.loncent.protocol.inner.CheckToken.internal_static_com_loncent_protocol_CheckTokenRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.loncent.protocol.inner.CheckToken.internal_static_com_loncent_protocol_CheckTokenRequest_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string accountName = 1;
    public static final int ACCOUNTNAME_FIELD_NUMBER = 1;
    private java.lang.Object accountName_;
    public boolean hasAccountName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getAccountName() {
      java.lang.Object ref = accountName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          accountName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getAccountNameBytes() {
      java.lang.Object ref = accountName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        accountName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int64 token = 2;
    public static final int TOKEN_FIELD_NUMBER = 2;
    private long token_;
    public boolean hasToken() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public long getToken() {
      return token_;
    }
    
    private void initFields() {
      accountName_ = "";
      token_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getAccountNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, token_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getAccountNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, token_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.loncent.protocol.inner.CheckToken.CheckTokenRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.loncent.protocol.inner.CheckToken.CheckTokenRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.loncent.protocol.inner.CheckToken.CheckTokenRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.loncent.protocol.inner.CheckToken.CheckTokenRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.loncent.protocol.inner.CheckToken.CheckTokenRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.loncent.protocol.inner.CheckToken.CheckTokenRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.loncent.protocol.inner.CheckToken.CheckTokenRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.loncent.protocol.inner.CheckToken.CheckTokenRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.loncent.protocol.inner.CheckToken.CheckTokenRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.loncent.protocol.inner.CheckToken.CheckTokenRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.loncent.protocol.inner.CheckToken.CheckTokenRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.loncent.protocol.inner.CheckToken.CheckTokenRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.loncent.protocol.inner.CheckToken.internal_static_com_loncent_protocol_CheckTokenRequest_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.loncent.protocol.inner.CheckToken.internal_static_com_loncent_protocol_CheckTokenRequest_fieldAccessorTable;
      }
      
      // Construct using com.loncent.protocol.inner.CheckToken.CheckTokenRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        accountName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        token_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.loncent.protocol.inner.CheckToken.CheckTokenRequest.getDescriptor();
      }
      
      public com.loncent.protocol.inner.CheckToken.CheckTokenRequest getDefaultInstanceForType() {
        return com.loncent.protocol.inner.CheckToken.CheckTokenRequest.getDefaultInstance();
      }
      
      public com.loncent.protocol.inner.CheckToken.CheckTokenRequest build() {
        com.loncent.protocol.inner.CheckToken.CheckTokenRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.loncent.protocol.inner.CheckToken.CheckTokenRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.loncent.protocol.inner.CheckToken.CheckTokenRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.loncent.protocol.inner.CheckToken.CheckTokenRequest buildPartial() {
        com.loncent.protocol.inner.CheckToken.CheckTokenRequest result = new com.loncent.protocol.inner.CheckToken.CheckTokenRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.accountName_ = accountName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.token_ = token_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.loncent.protocol.inner.CheckToken.CheckTokenRequest) {
          return mergeFrom((com.loncent.protocol.inner.CheckToken.CheckTokenRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.loncent.protocol.inner.CheckToken.CheckTokenRequest other) {
        if (other == com.loncent.protocol.inner.CheckToken.CheckTokenRequest.getDefaultInstance()) return this;
        if (other.hasAccountName()) {
          setAccountName(other.getAccountName());
        }
        if (other.hasToken()) {
          setToken(other.getToken());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              accountName_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              token_ = input.readInt64();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string accountName = 1;
      private java.lang.Object accountName_ = "";
      public boolean hasAccountName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getAccountName() {
        java.lang.Object ref = accountName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          accountName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setAccountName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        accountName_ = value;
        onChanged();
        return this;
      }
      public Builder clearAccountName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        accountName_ = getDefaultInstance().getAccountName();
        onChanged();
        return this;
      }
      void setAccountName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        accountName_ = value;
        onChanged();
      }
      
      // optional int64 token = 2;
      private long token_ ;
      public boolean hasToken() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public long getToken() {
        return token_;
      }
      public Builder setToken(long value) {
        bitField0_ |= 0x00000002;
        token_ = value;
        onChanged();
        return this;
      }
      public Builder clearToken() {
        bitField0_ = (bitField0_ & ~0x00000002);
        token_ = 0L;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.loncent.protocol.CheckTokenRequest)
    }
    
    static {
      defaultInstance = new CheckTokenRequest(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.loncent.protocol.CheckTokenRequest)
  }
  
  public interface CheckTokenResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string accountName = 1;
    boolean hasAccountName();
    String getAccountName();
    
    // optional int64 token = 3;
    boolean hasToken();
    long getToken();
    
    // optional int32 result = 2;
    boolean hasResult();
    int getResult();
  }
  public static final class CheckTokenResponse extends
      com.google.protobuf.GeneratedMessage
      implements CheckTokenResponseOrBuilder {
    // Use CheckTokenResponse.newBuilder() to construct.
    private CheckTokenResponse(Builder builder) {
      super(builder);
    }
    private CheckTokenResponse(boolean noInit) {}
    
    private static final CheckTokenResponse defaultInstance;
    public static CheckTokenResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public CheckTokenResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.loncent.protocol.inner.CheckToken.internal_static_com_loncent_protocol_CheckTokenResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.loncent.protocol.inner.CheckToken.internal_static_com_loncent_protocol_CheckTokenResponse_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string accountName = 1;
    public static final int ACCOUNTNAME_FIELD_NUMBER = 1;
    private java.lang.Object accountName_;
    public boolean hasAccountName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getAccountName() {
      java.lang.Object ref = accountName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          accountName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getAccountNameBytes() {
      java.lang.Object ref = accountName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        accountName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int64 token = 3;
    public static final int TOKEN_FIELD_NUMBER = 3;
    private long token_;
    public boolean hasToken() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public long getToken() {
      return token_;
    }
    
    // optional int32 result = 2;
    public static final int RESULT_FIELD_NUMBER = 2;
    private int result_;
    public boolean hasResult() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getResult() {
      return result_;
    }
    
    private void initFields() {
      accountName_ = "";
      token_ = 0L;
      result_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getAccountNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(2, result_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(3, token_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getAccountNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, result_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, token_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.loncent.protocol.inner.CheckToken.CheckTokenResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.loncent.protocol.inner.CheckToken.CheckTokenResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.loncent.protocol.inner.CheckToken.CheckTokenResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.loncent.protocol.inner.CheckToken.CheckTokenResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.loncent.protocol.inner.CheckToken.CheckTokenResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.loncent.protocol.inner.CheckToken.CheckTokenResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.loncent.protocol.inner.CheckToken.CheckTokenResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.loncent.protocol.inner.CheckToken.CheckTokenResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.loncent.protocol.inner.CheckToken.CheckTokenResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.loncent.protocol.inner.CheckToken.CheckTokenResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.loncent.protocol.inner.CheckToken.CheckTokenResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.loncent.protocol.inner.CheckToken.CheckTokenResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.loncent.protocol.inner.CheckToken.internal_static_com_loncent_protocol_CheckTokenResponse_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.loncent.protocol.inner.CheckToken.internal_static_com_loncent_protocol_CheckTokenResponse_fieldAccessorTable;
      }
      
      // Construct using com.loncent.protocol.inner.CheckToken.CheckTokenResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        accountName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        token_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        result_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.loncent.protocol.inner.CheckToken.CheckTokenResponse.getDescriptor();
      }
      
      public com.loncent.protocol.inner.CheckToken.CheckTokenResponse getDefaultInstanceForType() {
        return com.loncent.protocol.inner.CheckToken.CheckTokenResponse.getDefaultInstance();
      }
      
      public com.loncent.protocol.inner.CheckToken.CheckTokenResponse build() {
        com.loncent.protocol.inner.CheckToken.CheckTokenResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.loncent.protocol.inner.CheckToken.CheckTokenResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.loncent.protocol.inner.CheckToken.CheckTokenResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.loncent.protocol.inner.CheckToken.CheckTokenResponse buildPartial() {
        com.loncent.protocol.inner.CheckToken.CheckTokenResponse result = new com.loncent.protocol.inner.CheckToken.CheckTokenResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.accountName_ = accountName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.token_ = token_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.result_ = result_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.loncent.protocol.inner.CheckToken.CheckTokenResponse) {
          return mergeFrom((com.loncent.protocol.inner.CheckToken.CheckTokenResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.loncent.protocol.inner.CheckToken.CheckTokenResponse other) {
        if (other == com.loncent.protocol.inner.CheckToken.CheckTokenResponse.getDefaultInstance()) return this;
        if (other.hasAccountName()) {
          setAccountName(other.getAccountName());
        }
        if (other.hasToken()) {
          setToken(other.getToken());
        }
        if (other.hasResult()) {
          setResult(other.getResult());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              accountName_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000004;
              result_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000002;
              token_ = input.readInt64();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string accountName = 1;
      private java.lang.Object accountName_ = "";
      public boolean hasAccountName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getAccountName() {
        java.lang.Object ref = accountName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          accountName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setAccountName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        accountName_ = value;
        onChanged();
        return this;
      }
      public Builder clearAccountName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        accountName_ = getDefaultInstance().getAccountName();
        onChanged();
        return this;
      }
      void setAccountName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        accountName_ = value;
        onChanged();
      }
      
      // optional int64 token = 3;
      private long token_ ;
      public boolean hasToken() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public long getToken() {
        return token_;
      }
      public Builder setToken(long value) {
        bitField0_ |= 0x00000002;
        token_ = value;
        onChanged();
        return this;
      }
      public Builder clearToken() {
        bitField0_ = (bitField0_ & ~0x00000002);
        token_ = 0L;
        onChanged();
        return this;
      }
      
      // optional int32 result = 2;
      private int result_ ;
      public boolean hasResult() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getResult() {
        return result_;
      }
      public Builder setResult(int value) {
        bitField0_ |= 0x00000004;
        result_ = value;
        onChanged();
        return this;
      }
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000004);
        result_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.loncent.protocol.CheckTokenResponse)
    }
    
    static {
      defaultInstance = new CheckTokenResponse(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.loncent.protocol.CheckTokenResponse)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_loncent_protocol_CheckTokenRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_loncent_protocol_CheckTokenRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_loncent_protocol_CheckTokenResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_loncent_protocol_CheckTokenResponse_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020CheckToken.proto\022\024com.loncent.protocol" +
      "\"7\n\021CheckTokenRequest\022\023\n\013accountName\030\001 \001" +
      "(\t\022\r\n\005token\030\002 \001(\003\"H\n\022CheckTokenResponse\022" +
      "\023\n\013accountName\030\001 \001(\t\022\r\n\005token\030\003 \001(\003\022\016\n\006r" +
      "esult\030\002 \001(\005B\034\n\032com.loncent.protocol.inne" +
      "r"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_loncent_protocol_CheckTokenRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_loncent_protocol_CheckTokenRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_loncent_protocol_CheckTokenRequest_descriptor,
              new java.lang.String[] { "AccountName", "Token", },
              com.loncent.protocol.inner.CheckToken.CheckTokenRequest.class,
              com.loncent.protocol.inner.CheckToken.CheckTokenRequest.Builder.class);
          internal_static_com_loncent_protocol_CheckTokenResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_loncent_protocol_CheckTokenResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_loncent_protocol_CheckTokenResponse_descriptor,
              new java.lang.String[] { "AccountName", "Token", "Result", },
              com.loncent.protocol.inner.CheckToken.CheckTokenResponse.class,
              com.loncent.protocol.inner.CheckToken.CheckTokenResponse.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
