// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BaseMessage.proto

package com.loncent.protocol;

public final class BaseMessage {
  private BaseMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface InnerMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 command = 1;
    boolean hasCommand();
    int getCommand();
    
    // required bytes body = 2;
    boolean hasBody();
    com.google.protobuf.ByteString getBody();
    
    // optional int64 clientSessionId = 3;
    boolean hasClientSessionId();
    long getClientSessionId();
    
    // optional int32 gateTypeId = 4;
    boolean hasGateTypeId();
    int getGateTypeId();
    
    // optional int64 roleId = 5;
    boolean hasRoleId();
    long getRoleId();
    
    // optional string userName = 6;
    boolean hasUserName();
    String getUserName();
  }
  public static final class InnerMessage extends
      com.google.protobuf.GeneratedMessage
      implements InnerMessageOrBuilder {
    // Use InnerMessage.newBuilder() to construct.
    private InnerMessage(Builder builder) {
      super(builder);
    }
    private InnerMessage(boolean noInit) {}
    
    private static final InnerMessage defaultInstance;
    public static InnerMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public InnerMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.loncent.protocol.BaseMessage.internal_static_com_loncent_protocol_InnerMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.loncent.protocol.BaseMessage.internal_static_com_loncent_protocol_InnerMessage_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 command = 1;
    public static final int COMMAND_FIELD_NUMBER = 1;
    private int command_;
    public boolean hasCommand() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getCommand() {
      return command_;
    }
    
    // required bytes body = 2;
    public static final int BODY_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString body_;
    public boolean hasBody() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.google.protobuf.ByteString getBody() {
      return body_;
    }
    
    // optional int64 clientSessionId = 3;
    public static final int CLIENTSESSIONID_FIELD_NUMBER = 3;
    private long clientSessionId_;
    public boolean hasClientSessionId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public long getClientSessionId() {
      return clientSessionId_;
    }
    
    // optional int32 gateTypeId = 4;
    public static final int GATETYPEID_FIELD_NUMBER = 4;
    private int gateTypeId_;
    public boolean hasGateTypeId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getGateTypeId() {
      return gateTypeId_;
    }
    
    // optional int64 roleId = 5;
    public static final int ROLEID_FIELD_NUMBER = 5;
    private long roleId_;
    public boolean hasRoleId() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public long getRoleId() {
      return roleId_;
    }
    
    // optional string userName = 6;
    public static final int USERNAME_FIELD_NUMBER = 6;
    private java.lang.Object userName_;
    public boolean hasUserName() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public String getUserName() {
      java.lang.Object ref = userName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          userName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      command_ = 0;
      body_ = com.google.protobuf.ByteString.EMPTY;
      clientSessionId_ = 0L;
      gateTypeId_ = 0;
      roleId_ = 0L;
      userName_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasCommand()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBody()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, command_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, body_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, clientSessionId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, gateTypeId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(5, roleId_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getUserNameBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, command_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, body_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, clientSessionId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, gateTypeId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, roleId_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getUserNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.loncent.protocol.BaseMessage.InnerMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.loncent.protocol.BaseMessage.InnerMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.loncent.protocol.BaseMessage.InnerMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.loncent.protocol.BaseMessage.InnerMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.loncent.protocol.BaseMessage.InnerMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.loncent.protocol.BaseMessage.InnerMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.loncent.protocol.BaseMessage.InnerMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.loncent.protocol.BaseMessage.InnerMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.loncent.protocol.BaseMessage.InnerMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.loncent.protocol.BaseMessage.InnerMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.loncent.protocol.BaseMessage.InnerMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.loncent.protocol.BaseMessage.InnerMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.loncent.protocol.BaseMessage.internal_static_com_loncent_protocol_InnerMessage_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.loncent.protocol.BaseMessage.internal_static_com_loncent_protocol_InnerMessage_fieldAccessorTable;
      }
      
      // Construct using com.loncent.protocol.BaseMessage.InnerMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        command_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        body_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        clientSessionId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        gateTypeId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        roleId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        userName_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.loncent.protocol.BaseMessage.InnerMessage.getDescriptor();
      }
      
      public com.loncent.protocol.BaseMessage.InnerMessage getDefaultInstanceForType() {
        return com.loncent.protocol.BaseMessage.InnerMessage.getDefaultInstance();
      }
      
      public com.loncent.protocol.BaseMessage.InnerMessage build() {
        com.loncent.protocol.BaseMessage.InnerMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.loncent.protocol.BaseMessage.InnerMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.loncent.protocol.BaseMessage.InnerMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.loncent.protocol.BaseMessage.InnerMessage buildPartial() {
        com.loncent.protocol.BaseMessage.InnerMessage result = new com.loncent.protocol.BaseMessage.InnerMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.command_ = command_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.body_ = body_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.clientSessionId_ = clientSessionId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.gateTypeId_ = gateTypeId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.roleId_ = roleId_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.userName_ = userName_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.loncent.protocol.BaseMessage.InnerMessage) {
          return mergeFrom((com.loncent.protocol.BaseMessage.InnerMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.loncent.protocol.BaseMessage.InnerMessage other) {
        if (other == com.loncent.protocol.BaseMessage.InnerMessage.getDefaultInstance()) return this;
        if (other.hasCommand()) {
          setCommand(other.getCommand());
        }
        if (other.hasBody()) {
          setBody(other.getBody());
        }
        if (other.hasClientSessionId()) {
          setClientSessionId(other.getClientSessionId());
        }
        if (other.hasGateTypeId()) {
          setGateTypeId(other.getGateTypeId());
        }
        if (other.hasRoleId()) {
          setRoleId(other.getRoleId());
        }
        if (other.hasUserName()) {
          setUserName(other.getUserName());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasCommand()) {
          
          return false;
        }
        if (!hasBody()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              command_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              body_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              clientSessionId_ = input.readInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              gateTypeId_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              roleId_ = input.readInt64();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              userName_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 command = 1;
      private int command_ ;
      public boolean hasCommand() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getCommand() {
        return command_;
      }
      public Builder setCommand(int value) {
        bitField0_ |= 0x00000001;
        command_ = value;
        onChanged();
        return this;
      }
      public Builder clearCommand() {
        bitField0_ = (bitField0_ & ~0x00000001);
        command_ = 0;
        onChanged();
        return this;
      }
      
      // required bytes body = 2;
      private com.google.protobuf.ByteString body_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasBody() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.google.protobuf.ByteString getBody() {
        return body_;
      }
      public Builder setBody(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        body_ = value;
        onChanged();
        return this;
      }
      public Builder clearBody() {
        bitField0_ = (bitField0_ & ~0x00000002);
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }
      
      // optional int64 clientSessionId = 3;
      private long clientSessionId_ ;
      public boolean hasClientSessionId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public long getClientSessionId() {
        return clientSessionId_;
      }
      public Builder setClientSessionId(long value) {
        bitField0_ |= 0x00000004;
        clientSessionId_ = value;
        onChanged();
        return this;
      }
      public Builder clearClientSessionId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        clientSessionId_ = 0L;
        onChanged();
        return this;
      }
      
      // optional int32 gateTypeId = 4;
      private int gateTypeId_ ;
      public boolean hasGateTypeId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getGateTypeId() {
        return gateTypeId_;
      }
      public Builder setGateTypeId(int value) {
        bitField0_ |= 0x00000008;
        gateTypeId_ = value;
        onChanged();
        return this;
      }
      public Builder clearGateTypeId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        gateTypeId_ = 0;
        onChanged();
        return this;
      }
      
      // optional int64 roleId = 5;
      private long roleId_ ;
      public boolean hasRoleId() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public long getRoleId() {
        return roleId_;
      }
      public Builder setRoleId(long value) {
        bitField0_ |= 0x00000010;
        roleId_ = value;
        onChanged();
        return this;
      }
      public Builder clearRoleId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        roleId_ = 0L;
        onChanged();
        return this;
      }
      
      // optional string userName = 6;
      private java.lang.Object userName_ = "";
      public boolean hasUserName() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public String getUserName() {
        java.lang.Object ref = userName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          userName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUserName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        userName_ = value;
        onChanged();
        return this;
      }
      public Builder clearUserName() {
        bitField0_ = (bitField0_ & ~0x00000020);
        userName_ = getDefaultInstance().getUserName();
        onChanged();
        return this;
      }
      void setUserName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000020;
        userName_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:com.loncent.protocol.InnerMessage)
    }
    
    static {
      defaultInstance = new InnerMessage(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.loncent.protocol.InnerMessage)
  }
  
  public interface MinaMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 command = 1;
    boolean hasCommand();
    int getCommand();
    
    // required bytes body = 2;
    boolean hasBody();
    com.google.protobuf.ByteString getBody();
  }
  public static final class MinaMessage extends
      com.google.protobuf.GeneratedMessage
      implements MinaMessageOrBuilder {
    // Use MinaMessage.newBuilder() to construct.
    private MinaMessage(Builder builder) {
      super(builder);
    }
    private MinaMessage(boolean noInit) {}
    
    private static final MinaMessage defaultInstance;
    public static MinaMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public MinaMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.loncent.protocol.BaseMessage.internal_static_com_loncent_protocol_MinaMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.loncent.protocol.BaseMessage.internal_static_com_loncent_protocol_MinaMessage_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 command = 1;
    public static final int COMMAND_FIELD_NUMBER = 1;
    private int command_;
    public boolean hasCommand() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getCommand() {
      return command_;
    }
    
    // required bytes body = 2;
    public static final int BODY_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString body_;
    public boolean hasBody() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.google.protobuf.ByteString getBody() {
      return body_;
    }
    
    private void initFields() {
      command_ = 0;
      body_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasCommand()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBody()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, command_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, body_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, command_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, body_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.loncent.protocol.BaseMessage.MinaMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.loncent.protocol.BaseMessage.MinaMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.loncent.protocol.BaseMessage.MinaMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.loncent.protocol.BaseMessage.MinaMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.loncent.protocol.BaseMessage.MinaMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.loncent.protocol.BaseMessage.MinaMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.loncent.protocol.BaseMessage.MinaMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.loncent.protocol.BaseMessage.MinaMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.loncent.protocol.BaseMessage.MinaMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.loncent.protocol.BaseMessage.MinaMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.loncent.protocol.BaseMessage.MinaMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.loncent.protocol.BaseMessage.MinaMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.loncent.protocol.BaseMessage.internal_static_com_loncent_protocol_MinaMessage_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.loncent.protocol.BaseMessage.internal_static_com_loncent_protocol_MinaMessage_fieldAccessorTable;
      }
      
      // Construct using com.loncent.protocol.BaseMessage.MinaMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        command_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        body_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.loncent.protocol.BaseMessage.MinaMessage.getDescriptor();
      }
      
      public com.loncent.protocol.BaseMessage.MinaMessage getDefaultInstanceForType() {
        return com.loncent.protocol.BaseMessage.MinaMessage.getDefaultInstance();
      }
      
      public com.loncent.protocol.BaseMessage.MinaMessage build() {
        com.loncent.protocol.BaseMessage.MinaMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.loncent.protocol.BaseMessage.MinaMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.loncent.protocol.BaseMessage.MinaMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.loncent.protocol.BaseMessage.MinaMessage buildPartial() {
        com.loncent.protocol.BaseMessage.MinaMessage result = new com.loncent.protocol.BaseMessage.MinaMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.command_ = command_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.body_ = body_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.loncent.protocol.BaseMessage.MinaMessage) {
          return mergeFrom((com.loncent.protocol.BaseMessage.MinaMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.loncent.protocol.BaseMessage.MinaMessage other) {
        if (other == com.loncent.protocol.BaseMessage.MinaMessage.getDefaultInstance()) return this;
        if (other.hasCommand()) {
          setCommand(other.getCommand());
        }
        if (other.hasBody()) {
          setBody(other.getBody());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasCommand()) {
          
          return false;
        }
        if (!hasBody()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              command_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              body_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 command = 1;
      private int command_ ;
      public boolean hasCommand() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getCommand() {
        return command_;
      }
      public Builder setCommand(int value) {
        bitField0_ |= 0x00000001;
        command_ = value;
        onChanged();
        return this;
      }
      public Builder clearCommand() {
        bitField0_ = (bitField0_ & ~0x00000001);
        command_ = 0;
        onChanged();
        return this;
      }
      
      // required bytes body = 2;
      private com.google.protobuf.ByteString body_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasBody() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.google.protobuf.ByteString getBody() {
        return body_;
      }
      public Builder setBody(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        body_ = value;
        onChanged();
        return this;
      }
      public Builder clearBody() {
        bitField0_ = (bitField0_ & ~0x00000002);
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.loncent.protocol.MinaMessage)
    }
    
    static {
      defaultInstance = new MinaMessage(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.loncent.protocol.MinaMessage)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_loncent_protocol_InnerMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_loncent_protocol_InnerMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_loncent_protocol_MinaMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_loncent_protocol_MinaMessage_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021BaseMessage.proto\022\024com.loncent.protoco" +
      "l\"|\n\014InnerMessage\022\017\n\007command\030\001 \002(\005\022\014\n\004bo" +
      "dy\030\002 \002(\014\022\027\n\017clientSessionId\030\003 \001(\003\022\022\n\ngat" +
      "eTypeId\030\004 \001(\005\022\016\n\006roleId\030\005 \001(\003\022\020\n\010userNam" +
      "e\030\006 \001(\t\",\n\013MinaMessage\022\017\n\007command\030\001 \002(\005\022" +
      "\014\n\004body\030\002 \002(\014B\026\n\024com.loncent.protocol"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_loncent_protocol_InnerMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_loncent_protocol_InnerMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_loncent_protocol_InnerMessage_descriptor,
              new java.lang.String[] { "Command", "Body", "ClientSessionId", "GateTypeId", "RoleId", "UserName", },
              com.loncent.protocol.BaseMessage.InnerMessage.class,
              com.loncent.protocol.BaseMessage.InnerMessage.Builder.class);
          internal_static_com_loncent_protocol_MinaMessage_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_loncent_protocol_MinaMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_loncent_protocol_MinaMessage_descriptor,
              new java.lang.String[] { "Command", "Body", },
              com.loncent.protocol.BaseMessage.MinaMessage.class,
              com.loncent.protocol.BaseMessage.MinaMessage.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
